### ISSUE TITLE
Welp!

### ISSUE THREAD

**Issue by kheirmirza** [56-bits/Parts-depr#30]
I need to know what kind of art we are doing.I have no idea.

**Comment by kiesenverseist** [comment]
We haven't really decided on a theme but ill update the issues with the correct image dimensions.

Also this would have much better been as a comment on the related issue.

So basically feel free to draw what ever you think will fit but keep in mind that we may completely replace it if we can find a fitting theme.

**Comment by kheirmirza** [comment]
Cool story bruh!
